var djVenue = [
    {
        "venueID": 53,
        "venueName": "Aliga Beach",
        "venueAddress": "Aliga Beach  8171 Balatonvilágos",
        "venueLatitude": 0,
        "venueLongitude": 0,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "",
        "country": "Hungary"
    },
    {
        "venueID": 54,
        "venueName": "Alimentation Générale",
        "venueAddress": " 64 Rue Jean Pierre Timbaud, 75011 Paris",
        "venueLatitude": 48.8667163,
        "venueLongitude": 2.3744286,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "",
        "country": "France"
    },
    {
        "venueID": 55,
        "venueName": "Allee DES Pins - Plage",
        "venueAddress": " 66700 ARGELÈS SUR MER",
        "venueLatitude": 42.546214,
        "venueLongitude": 3.022911,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "",
        "country": "France"
    },
    {
        "venueID": 56,
        "venueName": "Allgäu Airport",
        "venueAddress": "Am Flughafen 31; Memmingerberg; Allgäu",
        "venueLatitude": 47.9864344,
        "venueLongitude": 10.2287652,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "",
        "country": "Germany"
    },
    {
        "venueID": 57,
        "venueName": "Alliant Energy Center",
        "venueAddress": "1919 Expo Way, Madison, WI",
        "venueLatitude": 43.0483897,
        "venueLongitude": -89.3832407,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "",
        "country": "United States of America"
    },
    {
        "venueID": 58,
        "venueName": "Allphones Arena",
        "venueAddress": " Olympic Blvd &amp; Edwin Flack Avenue, Sydney Olympic Park NSW 2127,",
        "venueLatitude": 37.8860322,
        "venueLongitude": -122.0756738,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "Sydney",
        "country": "Australia"
    },
    {
        "venueID": 59,
        "venueName": "Almere Beach",
        "venueAddress": " Strandweg, Almere",
        "venueLatitude": 52.3336926,
        "venueLongitude": 5.2139881,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "",
        "country": "Netherlands"
    },
    {
        "venueID": 60,
        "venueName": "Alpen Untn",
        "venueAddress": "Reutweg / Prad am Stilfserjoch (Vinschgau)",
        "venueLatitude": 46.6192942,
        "venueLongitude": 10.5933134,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "",
        "country": "Italy"
    },
    {
        "venueID": 61,
        "venueName": "Alpha Centauri",
        "venueAddress": " Sanatornaia 1, 230000 Grodno,",
        "venueLatitude": 53.6693538,
        "venueLongitude": 23.8131306,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "",
        "country": "Belarus"
    },
    {
        "venueID": 62,
        "venueName": "Alpincenter Wittenburg",
        "venueAddress": " Zur Winterwelt, 19243 Wittenburg,",
        "venueLatitude": 53.511243,
        "venueLongitude": 11.087625,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "",
        "country": "Germany"
    },
    {
        "venueID": 63,
        "venueName": "Alte Münze",
        "venueAddress": " Molkenmarkt 2; Mitte; 10179 Berlin;",
        "venueLatitude": 52.5161129,
        "venueLongitude": 13.4091199,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "",
        "country": "Germany"
    },
    {
        "venueID": 64,
        "venueName": "Altromondo Studios",
        "venueAddress": " Via Flaminia 358, 47924 Rimini (RN),",
        "venueLatitude": 44.0246301,
        "venueLongitude": 12.6178391,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "Rimini Rn",
        "country": "Italy"
    },
    {
        "venueID": 65,
        "venueName": "Alumbra",
        "venueAddress": " 9/161 Harbour Esplanade; Docklands, VIC 3008;",
        "venueLatitude": -37.8172856,
        "venueLongitude": 144.9460528,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "Docklands",
        "country": "Australia"
    },
    {
        "venueID": 66,
        "venueName": "Am Seelübber See 61 / 17291 Seelübbe",
        "venueAddress": " Am Seelübber See 61 / 17291 Seelübbe",
        "venueLatitude": 53.25699,
        "venueLongitude": 13.88211,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "",
        "country": "Germany"
    },
    {
        "venueID": 67,
        "venueName": "Amazura Concert Hall",
        "venueAddress": " 91-12 144th Place, Jamaica, NY 11435",
        "venueLatitude": 40.7001783,
        "venueLongitude": -73.8103899,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "Queens",
        "country": "United States of America"
    },
    {
        "venueID": 68,
        "venueName": "Ambasada Gavioli",
        "venueAddress": " 00 Koper, Izola,",
        "venueLatitude": 45.5257951,
        "venueLongitude": 13.6488304,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "Izola   Isola",
        "country": "Slovenia"
    },
    {
        "venueID": 69,
        "venueName": "Ambranight",
        "venueAddress": " Via Cala dAmbra, 08020 San Teodoro (OT)",
        "venueLatitude": 40.7699767,
        "venueLongitude": 9.6773444,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "",
        "country": "Italy"
    },
    {
        "venueID": 70,
        "venueName": "Amfiteatr",
        "venueAddress": " ul. Fredry, 78-100 Ko?obrzeg,",
        "venueLatitude": 54.1813348,
        "venueLongitude": 15.5923512,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "",
        "country": "Poland"
    },
    {
        "venueID": 71,
        "venueName": "Amnesia",
        "venueAddress": " Ctra. Ibiza a San Antonio, Km 5, 07816 San Rafael, Ibiza",
        "venueLatitude": 38.9558315,
        "venueLongitude": 1.4049592,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "Ibiza",
        "country": "Spain"
    },
    {
        "venueID": 72,
        "venueName": "Amnesia - Paris",
        "venueAddress": " 25 Rue De Larrivée; 75015; Paris;",
        "venueLatitude": 48.8424396,
        "venueLongitude": 2.3212913,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "Paris",
        "country": "France"
    },
    {
        "venueID": 73,
        "venueName": "Amnesia Milano",
        "venueAddress": " Via Alfonso Gatto angolo Viale Forlanini, 20134 Milano (MI),",
        "venueLatitude": 45.4621298,
        "venueLongitude": 9.2385295,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "",
        "country": "Italy"
    },
    {
        "venueID": 74,
        "venueName": "Amoeba Music Hollywood",
        "venueAddress": " 6400 Sunset Blvd, Los Angeles, CA 90028",
        "venueLatitude": 34.0977683,
        "venueLongitude": -118.3290738,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "Los Angeles",
        "country": "United States of America"
    },
    {
        "venueID": 75,
        "venueName": "Ampere",
        "venueAddress": " Simonsstraat 21, 2018 Antwerp, BE",
        "venueLatitude": 51.2127521,
        "venueLongitude": 4.4209746,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "Antwerp",
        "country": "Belgium"
    },
    {
        "venueID": 76,
        "venueName": "Amsterdam ArenA",
        "venueAddress": " Arena Boulevard 1; Zuidoost; Amsterdam;",
        "venueLatitude": 52.3143354,
        "venueLongitude": 4.9417927,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "Amsterdam",
        "country": "Netherlands"
    },
    {
        "venueID": 77,
        "venueName": "Amsterdam RAI",
        "venueAddress": " Europaplein 22; 1078 Zuideramstel; Amsterdam;",
        "venueLatitude": 52.3434177,
        "venueLongitude": 4.8916423,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "Amsterdam",
        "country": "Netherlands"
    },
    {
        "venueID": 78,
        "venueName": "Amsterdamse Bos",
        "venueAddress": " Nieuwe Meerlaan 3; 1182 Amstelveen; Amsterdam;",
        "venueLatitude": 52.3124545,
        "venueLongitude": 4.8210834,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "Amstelveen",
        "country": "Netherlands"
    },
    {
        "venueID": 79,
        "venueName": "Anaheim Convention Center",
        "venueAddress": " 800 E Katella Ave, Anaheim, CA 92805",
        "venueLatitude": 33.8032559,
        "venueLongitude": -117.8983956,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "",
        "country": "United States of America"
    },
    {
        "venueID": 80,
        "venueName": "Anaklia",
        "venueAddress": " Anaklia,",
        "venueLatitude": 0,
        "venueLongitude": 0,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "Batumi",
        "country": "Georgia"
    },
    {
        "venueID": 81,
        "venueName": "Ancol Eco Park",
        "venueAddress": "Ecovention Building - Ecopark, Jalan Lodan Timur No 7 Ancol Taman Impian, Jakarta Utara",
        "venueLatitude": 0,
        "venueLongitude": 0,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "Jakarta",
        "country": "Indonesia"
    },
    {
        "venueID": 82,
        "venueName": "And",
        "venueAddress": " 500 Oxford st, Bondi Junction NSW 2022,",
        "venueLatitude": -33.8914152,
        "venueLongitude": 151.2508154,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "",
        "country": "Australia"
    },
    {
        "venueID": 83,
        "venueName": "Andrómeda",
        "venueAddress": "Vila Real",
        "venueLatitude": 41.3010351,
        "venueLongitude": -7.7422354,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "",
        "country": "Portugal"
    },
    {
        "venueID": 84,
        "venueName": "Anfiteatro Puerto De La Libertad",
        "venueAddress": " Anfiteatro Puerto de La Libertad, La libertada",
        "venueLatitude": 0,
        "venueLongitude": 0,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "",
        "country": "El Salvador"
    },
    {
        "venueID": 85,
        "venueName": "Anfiteatro Tito Puente",
        "venueAddress": " Parque Luis Munoz Marin, San Juan 00918,",
        "venueLatitude": 18.4110733,
        "venueLongitude": -66.0723754,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "",
        "country": "Puerto Rico"
    },
    {
        "venueID": 86,
        "venueName": "Angar",
        "venueAddress": " Kemerovskaya 1/3, Omsk,",
        "venueLatitude": 54.998269,
        "venueLongitude": 73.347669,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "",
        "country": "Russia"
    },
    {
        "venueID": 87,
        "venueName": "Anhembi",
        "venueAddress": " Av. Olavo Fontoura, 1209; São Paulo, 02012-021;",
        "venueLatitude": -23.5157253,
        "venueLongitude": -46.6404566,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "Sao Paulo",
        "country": "Brazil"
    },
    {
        "venueID": 88,
        "venueName": "Anita Dee II",
        "venueAddress": " 200 N Breakwater Access; Chicago; IL 60601",
        "venueLatitude": 41.8879472,
        "venueLongitude": -87.6128627,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "",
        "country": "United States of America"
    },
    {
        "venueID": 89,
        "venueName": "Anthem",
        "venueAddress": " 125 12th Avenue North, Nashville, TN USA",
        "venueLatitude": 36.1576442,
        "venueLongitude": -86.7885424,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "",
        "country": "United States of America"
    },
    {
        "venueID": 90,
        "venueName": "Antique Theatro - Sevilla",
        "venueAddress": " Antique Theatro - Sevilla - Andalucia",
        "venueLatitude": 0,
        "venueLongitude": 0,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "",
        "country": "Spain"
    },
    {
        "venueID": 91,
        "venueName": "Anzuclub",
        "venueAddress": " AvenidaTiradentes 2555, Parque Industrial Itu, São Paulo, 13309-640,",
        "venueLatitude": -23.2955964,
        "venueLongitude": -47.3005647,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "",
        "country": "Brazil"
    },
    {
        "venueID": 92,
        "venueName": "Apple Bar",
        "venueAddress": " 5-9 Synagogue Place; Adelaide SA 5000;",
        "venueLatitude": -34.9223393,
        "venueLongitude": 138.6065615,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "",
        "country": "Australia"
    },
    {
        "venueID": 93,
        "venueName": "Aquabest",
        "venueAddress": " Ekkersweyer 1, 5681 RZ, Best, Eindhoven,",
        "venueLatitude": 51.5006786,
        "venueLongitude": 5.4389608,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "Best",
        "country": "Netherlands"
    },
    {
        "venueID": 94,
        "venueName": "Aquafan Riccione",
        "venueAddress": " via Ascoli Piceno 6, 47838 Riccione (RN)",
        "venueLatitude": 43.986006,
        "venueLongitude": 12.646851,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "Riccione",
        "country": "Italy"
    },
    {
        "venueID": 95,
        "venueName": "Aqualand Mallorca",
        "venueAddress": "Aqualand Arenal, Mallorca",
        "venueLatitude": 0,
        "venueLongitude": 0,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "",
        "country": "Spain"
    },
    {
        "venueID": 96,
        "venueName": "Aquapark Moosburg",
        "venueAddress": "Sempt 20, 85368 Moosburg",
        "venueLatitude": 0,
        "venueLongitude": 0,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "Moosburg",
        "country": "Germany"
    },
    {
        "venueID": 97,
        "venueName": "Aquarius Zagreb",
        "venueAddress": " Aleja Matije Ljubeka 10000, Zagreb,",
        "venueLatitude": 45.7853163,
        "venueLongitude": 15.9176551,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "",
        "country": "Croatia"
    },
    {
        "venueID": 98,
        "venueName": "Aquasella Festival",
        "venueAddress": "Arriondas - Asturias",
        "venueLatitude": 43.387576,
        "venueLongitude": -5.1882633,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "Arriondas",
        "country": "Spain"
    },
    {
        "venueID": 99,
        "venueName": "Aragon Ballroom",
        "venueAddress": " 1106 West Lawrence Avenue, Chicago, IL",
        "venueLatitude": 41.9693569,
        "venueLongitude": -87.6578703,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "Chicago",
        "country": "United States of America"
    },
    {
        "venueID": 100,
        "venueName": "Arcosanti",
        "venueAddress": "HC74, Box 4136, Mayer, AZ 86333",
        "venueLatitude": 0,
        "venueLongitude": 0,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "",
        "country": "United States of America"
    },
    {
        "venueID": 101,
        "venueName": "Area",
        "venueAddress": " 67 Albert Embankment; Vauxhall; London SE1 7TP;",
        "venueLatitude": 51.4869736,
        "venueLongitude": -0.1232856,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "Sheffield",
        "country": "United Kingdom"
    },
    {
        "venueID": 102,
        "venueName": "Arena",
        "venueAddress": " 6655 Santa Monica Blvd, Hollywood, CA 90038",
        "venueLatitude": 34.0909153,
        "venueLongitude": -118.3351884,
        "venueBands": 0,
        "venueResident": 0,
        "venueGigatools": "",
        "venueSongkick": 0,
        "city": "Chandler",
        "country": "United States of America"
    }
];